"""Initial schema creation

Revision ID: 28a546de915e
Revises: 
Create Date: 2026-05-12 21:55:19.002804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28a546de915e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('mentioned', sa.Boolean(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('mention_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mention_model_date', 'mentions', ['ai_model', 'mention_date'], unique=False)
    op.create_index(op.f('ix_mentions_ai_model'), 'mentions', ['ai_model'], unique=False)
    op.create_index(op.f('ix_mentions_mention_date'), 'mentions', ['mention_date'], unique=False)
    op.create_index(op.f('ix_mentions_mentioned'), 'mentions', ['mentioned'], unique=False)
    op.create_index(op.f('ix_mentions_rank_position'), 'mentions', ['rank_position'], unique=False)
    op.create_index(op.f('ix_mentions_sentiment'), 'mentions', ['sentiment'], unique=False)
    op.create_table('sentiment_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('color_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentiment_types')
    op.drop_index(op.f('ix_mentions_sentiment'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_rank_position'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_mentioned'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_mention_date'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_ai_model'), table_name='mentions')
    op.drop_index('ix_mention_model_date', table_name='mentions')
    op.drop_table('mentions')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
